ESPACIO = '..'

TORRE_NEGRA = 'TO'
CABALLO_NEGRO = 'CA'
ALFIL_NEGRO = 'AL'
REINA_NEGRA = 'QU'
REY_NEGRO = 'KI'
PEON_NEGRO = 'PE'

TORRE_BLANCA = 'to'
CABALLO_BLANCO = 'ca'
ALFIL_BLANCO = 'al'
REINA_BLANCA = 'qu'
REY_BLANCO = 'ki'
PEON_BLANCO = 'pe'

BLANCAS = (
    TORRE_BLANCA,
    CABALLO_BLANCO,
    ALFIL_BLANCO,
    REINA_BLANCA,
    REY_BLANCO,
    PEON_BLANCO,
)

NEGRAS = (
    TORRE_NEGRA,
    CABALLO_NEGRO,
    ALFIL_NEGRO,
    REINA_NEGRA,
    REY_NEGRO,
    PEON_NEGRO,
)
